version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine # Sử dụng bản alpine cho nhẹ
    container_name: postgres_test_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ubuntu8s9reat
      POSTGRES_DB: test # Tên database khởi tạo ban đầu
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  # --- THÊM REDIS VÀO ĐÂY ---
  redis_cache:
    image: redis:alpine # Bản alpine siêu nhẹ (~30MB)
    container_name: redis_test_container
    ports:
      - "6379:6379" # Kéo port 6379 ra máy thật nếu bạn muốn dùng Redis Desktop Manager để check
    volumes:
      - redis_data:/data # Lưu dữ liệu Redis không bị mất khi restart container

  flask_backend:
    build: . # Docker sẽ tự tìm file Dockerfile ở cùng thư mục để build
    container_name: flask_test_container
    ports:
      - "5000:5000" # Kéo port 5000 ra ngoài máy thật như bạn muốn
    volumes:
      - .:/app # Mount code từ máy thật vào container để khi bạn sửa code không cần build lại
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:ubuntu8s9reat@postgres_db:5432/test
    depends_on:
      - postgres_db
      - redis_cache # Thêm Redis vào đây để Flask đợi cả Postgres và Redis chạy xong

volumes:
  postgres_data:
  redis_data: # Khai báo volume cho Redis ở cuối file
