version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine # Sử dụng bản alpine cho nhẹ
    container_name: postgres_test_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ubuntu8s9reat
      POSTGRES_DB: test # Tên database khởi tạo ban đầu
    ports:
      - "5432:5432"
    volumes:
      # Mount cả thư mục db-init vào thư mục tự động chạy của Docker
      - ./db-init:/docker-entrypoint-initdb.d
      # Lưu dữ liệu ở ổ cứng máy để nếu tắt docker đi bật lại không bị mất data
      - postgres_data:/var/lib/postgresql/data

  flask_backend:
    build: . # Docker sẽ tự tìm file Dockerfile ở cùng thư mục để build
    container_name: flask_test_container
    ports:
      - "5000:5000" # Kéo port 5000 ra ngoài máy thật như bạn muốn
    volumes:
      - .:/app # Mount code từ máy thật vào container để khi bạn sửa code không cần build lại
    environment:
      - FLASK_ENV=development
      # Cách để Flask kết nối với Postgres (Sử dụng tên service làm host)
      - DATABASE_URL=postgresql://postgres:ubuntu8s9reat@postgres_db:5432/test
    depends_on:
      - postgres_db # Chờ container postgres chạy trước rồi mới bật Flask

volumes:
  postgres_data: